version: "3"
services:
  reverseproxy:
      image: stormcode/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: stormcode/userdata
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: "postgres"
      POSTGRESS_PASSWORD: "postgres" 
      POSTGRESS_DB: "postgres"
      POSTGRESS_HOST: "udagram.cbvw7jledvd0.us-west-2.rds.amazonaws.com"
      AWS_REGION: "ap-south-1" 
      AWS_PROFILE: "default" 
      AWS_BUCKET: "udagram512"
      JWT_SECRET: "helloworld"
      URL: "http://localhost:8100"
  backend-feed:
    image: stormcode/userfeed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: "postgres"
      POSTGRESS_PASSWORD: "postgres"
      POSTGRESS_DB: "postgres"
      POSTGRESS_HOST: "udagram.cbvw7jledvd0.us-west-2.rds.amazonaws.com" 
      AWS_REGION: "ap-south-1"
      AWS_PROFILE: "default" 
      AWS_BUCKET: "udagram512"
      JWT_SECRET: "helloworld"
      URL: "http://localhost:8100"
  frontend:
    image: stormcode/udacity-frontend 
    ports:
      - "8100:80"
